[package]
name = "systest"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
jni-gen = { path = ".." }
error-chain = "0.12.0"
env_logger = "0.5.13"
reqwest = "=0.9.1"
libflate = "=0.1.13"
tempdir = "0.3.5"

[dependencies]
error-chain = "0.12.0"
jni = { version = "0.11.0", features = ["backtrace", "invocation"] }
