[package]
name = "vir"
version = "0.1.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"

[dependencies]
index_vec = { version = "0.1.2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
derivative = "2.1.3"
regex = "1.7"
syn = { version = "1.0", features = ["full", "fold", "parsing", "derive"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
uuid = { version = "1.0", features = ["v4"] }
log = { version = "0.4", features = ["release_max_level_info"] }
lazy_static = "1.4.0"
itertools = "0.11"
derive_more = "0.99.16"
rustc-hash = "1.1.0"
tracing = { path = "../tracing" }

[build-dependencies]
vir-gen = { path = "../vir-gen" }
walkdir = "2.3.1"
