[package]
name = "vir"
version = "0.1.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"

[lib]
doctest = false # we have no doc tests

[dependencies]
prusti-rustc-interface = { path = "../prusti-rustc-interface" }
vir-proc-macro = { path = "../vir-proc-macro" }
bumpalo = { version = "3.12.0" }
prusti-interface = { path = "../prusti-interface" }
sealed = "0.5"

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]
rustc_private = true
