[package]
name = "vir"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"

[dependencies]
index_vec = { version = "0.1.2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rsmt2 = { git = "https://github.com/vakaras/rsmt2", branch = "labels" }
thiserror = "1.0.23"
derivative = "2.1.3"
syn = { version = "1.0", features = ["full", "fold", "parsing", "derive"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }

[build-dependencies]
vir-gen = { path = "../vir-gen" }
syn = { version = "1.0", features = ["full", "fold", "parsing", "derive"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
walkdir = "2.3.1"
