[workspace]
members = [
    "analysis",
    "prusti",
    "prusti-contracts",
    "prusti-contracts-impl",
    "prusti-contracts-internal",
    "prusti-specs",
    "prusti-tests",
    "prusti-common",
    "prusti-interface",
    "prusti-viper",
    "prusti-server",
    "prusti-launch",
    "test-crates",
    "viper",
    "viper-sys",
    "jni-gen",
	"jni-gen/systest",
]

exclude = [
    "prusti-contracts-test",
]

[profile.release]
# Enable after fixing https://github.com/viperproject/prusti-dev/issues/383
# lto = true
# codegen-units = 1
