[workspace]
members = [
    "prusti",
    "prusti-contracts",
    "prusti-contracts-impl",
    "prusti-contracts-internal",
    "prusti-specs",
    "prusti-tests",
    "prusti-common",
    "prusti-interface",
    "prusti-viper",
    "prusti-server",
    "prusti-launch",
    "viper",
    "viper-sys",
    "jni-gen",
	"jni-gen/systest",
]

exclude = [
    "prusti-contracts-test",
]

[profile.release]
# Enable after Rust's issue 50324
# https://github.com/rust-lang/rust/issues/50324
# lto = true
