[workspace]
members = [
	"viper",
	"viper-sys",
	"prusti-contracts",
	"prusti",
	"prusti-viper",
	"jni-gen",
	"jni-gen/systest",
	"prusti-interface",
	"prusti-filter",
]

[profile.release]
# Enable after Rust's issue 50324
# https://github.com/rust-lang/rust/issues/50324
# lto = true
