[package]
name = "test-crates"
version = "0.1.0"
authors = ["Federico Poli <federpoli@gmail.com>"]
edition = "2018"

[dependencies]
prusti-launch = { path = "../prusti-launch" }
prusti = { path = "../prusti" }
color-backtrace = "0.5.0"
rustwide = "0.11.0"
env_logger = "0.8.2"
log = "0.4.14"
csv = "1.1.5"
serde = "1.0.117"
toml = "0.5.8"
