[package]
name = "test-crates"
version = "0.1.0"
authors = ["Federico Poli <federpoli@gmail.com>"]
edition = "2018"

[dependencies]
prusti-launch = { path = "../prusti-launch" }
prusti = { path = "../prusti" }
color-backtrace = "0.4.2"
rustwide = "0.10.0"
env_logger = "0.8.1"
log = "0.4.0"
csv = "1.1.4"
serde = "1.0.117"
