[package]
name = "prusti-contracts-proc-macros"
version = "0.2.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"
license = "MPL-2.0"
description = "Internal `proc-macro` Prusti crate"
homepage = "https://www.pm.inf.ethz.ch/research/prusti.html"
repository = "https://github.com/viperproject/prusti-dev/tree/master/prusti-contracts/prusti-contracts-proc-macros/"
readme = "README.md"
keywords = ["prusti"]
categories = ["development-tools", "development-tools::testing"]

[lib]
proc-macro = true

[dependencies]
prusti-specs = { path = "../prusti-specs", version = "0.2.0", optional = true }
proc-macro2 = { version = "1.0", optional = true }

[features]
# Are we being compiled by Prusti and should include dependency on
# prusti-specs and proc-macro2?
prusti = ["dep:prusti-specs", "dep:proc-macro2"]
