[package]
name = "prusti-specs"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"

[lib]
doctest = false # we have no doc tests

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits", "visit-mut", "parsing", "printing"] }
quote = "1.0"
proc-macro2 = "1.0.24"
uuid = { version = "0.8", features = ["v4", "serde"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
