[workspace]
members = [
    "prusti-contracts",
    "prusti-contracts-std",
]

# This should not be built as part of Prusti
# It would require setting the `build.rustc-wrapper` in a `../.cargo/config.toml` correctly
# But it's unclear how to figure out if we're doing a debug or release build there
