# This will probably not need to be changed very often.
# Update this if e.g. the extern_specs require some
# minimum version of Prusti.
min_prusti_version = "0.2.2"

# Used when this is a local dep, of e.g. test crates
no_verify = true
