[package]
name = "tracing"
version = "0.1.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
tracing = { version = "0.1", features = ["log"] }
proc-macro-tracing = { path = "proc-macro-tracing" }
