[package]
name = "systest"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
jni-gen = { path = ".." }
error-chain = "0.12.0"
env_logger = "0.8.1"
ureq = "1.0.0"
tempdir = "0.3.5"

[dependencies]
error-chain = "0.12.0"
jni = { version = "0.17.0", features = ["backtrace", "invocation"] }
