[package]
name = "prusti-std"
version = "0.2.0"
authors = ["Prusti Devs <prusti_developers@sympa.ethz.ch>"]
edition = "2021"
license = "MPL-2.0"
description = "External specifications for items in std for Prusti"
homepage = "https://www.pm.inf.ethz.ch/research/prusti.html"
repository = "https://github.com/viperproject/prusti-dev/tree/master/prusti-contracts/prusti-std/"
readme = "README.md"
keywords = ["prusti", "contracts", "verification", "formal", "specifications"]
categories = ["development-tools", "development-tools::testing"]

[dependencies]
prusti-contracts = { path = "../prusti-contracts", version = "0.2.0" }

# Forward "prusti" flag
[features]
prusti = ["prusti-contracts/prusti"]
