[package]
name = "smt-log-analyzer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "smt-log-analyzer"
path = "src/analyzer.rs"
test = false # we have no unit tests
doctest = false # and no doc tests

[dependencies]
csv = "1.1.6"
