name: Build GitHub pages

on:
  workflow_dispatch:
  push:
    branches: [master, staging, trying]
    paths: 'docs/**'
  pull_request:
    branches: [master]
    paths: 'docs/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: --verbose --no-progress './**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Spellcheck
      #  uses: rojopolis/spellcheck-github-actions@0.27.0

  mdbook_test: # https://rust-lang.github.io/mdBook/continuous-integration.html
    runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            path: "repo"

        - name: Setup mdBook
          uses: peaceiris/actions-mdbook@v1
          with:
            mdbook-version: "latest"

        #  cargo should be installed (TODO: Maybe have to add a rustup toolchain file (for correct version locks))

        - name: Build dummy crate to get dependencies
          run: |
            cd repo/docs/dummy/
            cargo build

        - name: Doctest user guide
          run: |
            cd repo/docs/user-guide
            mdbook test -L "../../dummy/target/debug/deps/"

        - name: Doctest dev guide
          run: |
            cd repo/docs/dev-guide
            mdbook test -L "../../dummy/target/debug/deps/"

  deploy:
    # Only deploy on push to master
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: "repo"

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Prepare output directory
        run: |
          mkdir -p output

      - name: Build user guide
        run: |
          cd repo/docs/user-guide
          mdbook build -d ../../../output/user-guide

      - name: Build dev guide
        run: |
          cd repo/docs/dev-guide
          mdbook build -d ../../../output/dev-guide

      - name: Copy static content
        run: |
          cp -r repo/docs/static/* output

      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: true
